const answerList = [
    "NEURO",
    "VEDAL",
    "EVIL",
    "TUTEL",
    "ELIV",
    "NERE",
    "FILTERSAMA",
    "NEUROSAMA",
    "NURU",
    "FILTERED",
    "HUMBLE",
    "HIYORI",
    "COOKIE",
    "SUBTITLES",
    "ABANDONEDARCHIVE",
    "BREAD",
    "SPIN",
    "ALEX",
    "KOKO",
    "CAMILA",
    "CAMIMI",
    "MINI",
    "MINIKOMEW",
    "CERBER",
    "HEART",
    "BACKSLASH",
    "ANNY"
];
export default answerList;
//# sourceMappingURL=answers.js.map